project:
  type: website

website:
  title: "SJ"
  favicon: blueshell.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ref.qmd
        text: Reference

format:
  html:
    theme: lux
    css: styles.css
    toc: true



