project:
  type: website
  execute-dir: file

execute: 
  freeze: auto

website:
  title: "SJ"
  favicon: blueshell.png
  site-url: https://sarahjohnson.io
  repo-url: https://github.com/sj-io/sarahjohnsonIO
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: packages.qmd
        text: Packages
      - href: about/index.qmd
        text: About
    right: 
      - icon: github
        href: https://github.com/sj-io
      - icon: linkedin
        href: https://linkedin.com/in/sj-io
      - icon: controller
        href: https://sarah.fyi/
  body-footer: <script data-goatcounter="https://sarahjohnson.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: 
      light: [morph, custom.scss, theme-light.scss]
      dark: [morph, custom.scss, theme-dark.scss]
    
comments: 
  giscus:
    repo: sj-io/sarahjohnsonIO
