project:
  type: website
  execute-dir: file

execute: 
  freeze: auto

author: 
  - name: Sarah Johnson
    url: https://sarahjohnson.io

website:
  title: "SJ"
  favicon: blueshell.png
  site-url: https://sarahjohnson.io
  repo-url: https://github.com/sj-io/sarahjohnsonIO
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: housing.qmd
        text: Housing
      - href: r.qmd
        text: R Analysis
    right: 
      - icon: twitter
        href: https://twitter.com/sarahjohnson_io
      - icon: github
        href: https://github.com/sj-io
      - icon: linkedin
        href: https://linkedin.com/in/sj-io
      - icon: controller
        href: https://sarah.fyi/
  body-footer: <script data-goatcounter="https://sarahjohnson.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: [morph, custom.scss]
    
comments: 
  hypothesis: true

